### ISSUE TITLE
More currencies

### ISSUE THREAD

**Issue by sniperle** [EvanRespaut/Equate#1]
Please add more (all?) currencies, thanks.

**Comment by EvanRe** [comment]
More currencies is on the to do list.  I was thinking of using http://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote and loading all those in, but then it would probably need a search too haha.  Also would like to keep the existing api call in case that yahoo one breaks.

**Comment by livia-b** [comment]
I was going to ask exactly the same thing ( at least add CHF) , and also the possibility to remove currencies from the menu for a less cluttered interface

**Comment by EvanRe** [comment]
I'll be adding ~170 currencies next release!  Although CHF (Swiss Francs) are actually already in there, are they not appearing for you?  

Do you mean removing currencies buttons from the grid of 10 unit buttons (maybe knocking it down to 1 row of 5 instead of 2?  It would be tricky hide a row in a way that's obvious to the user, maybe a swipe down motion?  That wouldn't be very intuitive though.  Speaking of not intuitive, you can actually hold down a unit button to change it to one of the overflow units in the More menu.  Not an obvious feature, but handy once you know it's there :)

**Comment by livia-b** [comment]
Yes sorry, i don't know how i could have missed the chf! What i meant is to hold down the unit button and have a menu like "move to other", and then have that button become blank (for example i know that i need only 2/3 currencies most of the time, so a semi empty grid is simpler to use)

**Comment by sirex** [comment]
+1 for more (all) currencies. I would like to have some no longer existing currencies too. For example in Lithuanian LTL currency recently was replaced by EUR, but still it is useful to have LTL available, just to change old prices.

Great app! Thanks.

**Comment by EvanRespaut** [comment]
Just updated the app with ~175 extra currencies.  As an fyi, the last 3 used currencies will appear at the top of the list when you click more, hopefully that'll make it easier find the frequently used.  Let me know what you all think and if there are issues! :)

**Comment by sirex** [comment]
Just updated and tried how it works. Awesome, now I can find all currencies I need. Thanks!

Couple of things:

1. 9 last used currencies in main currency listing would be much more convenient.

2. 1 EUR to LTL gives 3.3589049, this is not right, because official and never changing value should be 3.45280. See http://euras.lt/en/ . Not sure what source you are using, but mostly sources provide currency prices for selling and for buying, so I guess 3.3589 is the buying price.

**Comment by sniperle** [comment]
Great - thanks  :-)

**Comment by EvanRespaut** [comment]
Glad to hear it.

Sirex, for the last used 9 currencies as buttons, this might have the undesired effect of sort of the buttons moving around without you wanting them to, depending on how it was done.  It's an interesting idea, and I will definitely consider it.  

As for the price of LTL, you are correct.  I'm using Yahoo's prices, who look like they do the conversion [wrong](http://finance.yahoo.com/currency-converter/?bypass=true#from=EUR;to=LTL;amt=1), as does [google](https://www.google.com/search?q=eur+to+ltl&oq=eur+to+ltl&aqs=chrome.0.69i59j0l5.1820j0j4&sourceid=chrome&es_sm=122&ie=UTF-8).  What's going on here is the value of LTL that I'm using from Yahoo is dollars to LTL on June 22, 2015 (not sure why it has that date).  But when you convert dollars to EUR using the current conversion rate of ~.906 instead of that from June 22, 2015 of ~.88, you get ~3.36 instead of 3.45280.  I'll look into adding a fix to this (probably the same thing is occurring for other obsoleted currencies).
